version: '3'

services:
  frontend:
    build: ./client
    container_name: front
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    depends_on:
      - backend
    networks:
      - mern-net

  backend:
    build: ./api
    container_name: backend
    restart: always
    ports:
      - 8800:8800
    networks:
      - mern-net
  
networks:
  mern-net:
    driver : bridge
